spring.application.name=productjpa



#testing localcomputer
#server.port=8083

#for render
server.port=${PORT:8080}


#POSTGRE SQL SETTING #
#spring.datasource.url=jdbc:postgresql://localhost:5000/productdb
#spring.datasource.username=postgres
#spring.datasource.password=root1234!

#for render
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
Spring.datasource.driver-class-name=org.postgresql.driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB