spring.application.name=productjpa



#testing localcomputer
server.port=8083

#for railway
#server.port=${PORT:8080}


#mARIA DATABASE SETTING
#spring.datasource.url=jdbc:mariadb://localhost:3306/productdb
#spring.datasource.username=root
#spring.datasource.password=root1234!

#POSTGRE SQL SETTING #
spring.datasource.url=jdbc:postgresql://localhost:5000/productdb
spring.datasource.username=postgres
spring.datasource.password=root1234!

#for railway
#spring.datasource.url=jdbc:postgresql://${PGPORT}/${PGTDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
#Spring.datasource.driver-class-name=org.postgresql.driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB